### PR TITLE
Updated Instagram service to latest API requirements and added default conf

### PR DESCRIPTION
**Pull request by Warrows**
Not much change in the config. However the Instagram API is now waiting for an oauth access token instead of the app client id. The wiki page should be changed to reflect that after the pull request is merged. Documentation this way : https://www.instagram.com/developer/authentication/

### CODE REVIEW

**Comment by HDValentin** [comment]
I have made all the changes and got an access_token. On the first run I get the message "
Warning: file_get_contents(https://api.instagram.com/v1/users/search?q=hdvalentin&count=1&access_token=correct access token): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in /var/www/virtual/bachem/html/PubwichFork/app/services/Instagram.php on line 29"

**Comment by Warrows** [comment]
@HDValentin From your error message you probably don't have a valid access token in your configuration.

**Comment by HDValentin** [comment]
I've removed it here. But in configuration it is correct.

**Comment by Warrows** [comment]
There is definitely a problem with your access token. If I paste this URL and use my own token I get a 200 response from Instagram.

**Comment by HDValentin** [comment]
Sorry you're wright. When calling with my token I get the following message;
"This request requires scope=public_content, but this access token is not authorized with this scope. The user must re-authorize your application with scope=public_content to be granted this permissions."

Can you please tell me what I have to do? 

When I go to the permissions page I get the following message: "You do not need to submit for review for this use case. If you are a developer and you want to display Instagram content on your website, then you do not need to submit your app for review. By using a client in sandbox mode, you can still access the last 20 media of any sandbox user that grants you permission."

**Comment by Warrows** [comment]
The link I pointed in my first comment (https://www.instagram.com/developer/authentication/) to this pull request contains a link (https://www.instagram.com/developer/authorization/) which explicits the process of setting your scope. The service will need the public scope to get your user id from your username. And while you are at it, there is no reason not to put all scopes since you are the only user of your app.
Anyway, thanks for your testing, it makes it clear that this is missing in the documentation. But since it's not merged yet, it would not makes sense to be in the wiki yet.
And while I can imagine that you want some specific features, there is a reason why we have dev versions, and moreover unmerged code. Maybe you should stick with the stable version, or avoid merging untested code if you don't want to be involved in testing an url or going through a documentation page. 
Lastly, I can't say I am very used to the whole pull request system on github, but I don't think its purpose is to offer support. 
Cheers.


**(Closing the pull request because the default config clearly needs more doc before merging)**

**Comment by HDValentin** [comment]
Thanks for your time. This all is not easy to comprehend, even for an experienced user.

**Comment by haschek** [comment]
I'm going to merge it so I re-open the pull request. We need to deal with the Instagram API changes anyway. I'm a little bit disappointed that we are forced to use the Oauth token of a user by the API endpoint but I have hope to be able to add another service method for simpler access to public data.

**Comment by haschek** [comment]
@HDValentin and @Warrows Could you please verify documentation steps with the latest `development` branch?

https://github.com/haschek/PubwichFork/wiki/ServiceInstagram

**Comment by HDValentin** [comment]
https://www.instagram.com/developer/authentication/
Only Server-side (Explicit) Flow worked. 

When I tried the Client-Side (Implicit) Authentication first I've got the following error message when using the Access Token:
"This request requires scope=public_content, but this access token is not authorized with this scope. The user must re-authorize your application with scope=public_content to be granted this permissions."

**Comment by haschek** [comment]
@HDValentin Did you used the URL from step 3? `https://api.instagram.com/oauth/authorize/?client_id=YOUR-CLIENT-ID&redirect_uri=YOUR-REDIRECT-URI&scope=basic+public_content&response_type=token`

`public_content` is part of the scope ...

**Comment by HDValentin** [comment]
I think, that was the problem, sorrx. I've used this one: https://api.instagram.com/oauth/authorize/?client_id=CLIENT-ID&redirect_uri=REDIRECT-URI&response_type=token

**Pull request merged**
